{"uuid": "84012624-79f9-4253-9920-0819044b9a9c", "children": ["8b6254bc-67de-4939-8519-d2b9cd2c8bf3"], "befores": [{"name": "temp_user", "status": "passed", "steps": [{"name": "Click Add User button", "status": "passed", "start": 1758528649329, "stop": 1758528651875}, {"name": "Add new user: 'test_admin_1758528649'", "status": "passed", "steps": [{"name": "Select option ''Admin'' from dropdown: ('xpath', \"//label[text()='User Role']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")", "status": "passed", "steps": [{"name": "Find element: ('xpath', \"//label[text()='User Role']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//label[text()='User Role']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")"}], "start": 1758528651878, "stop": 1758528651958}], "parameters": [{"name": "locator", "value": "('xpath', \"//label[text()='User Role']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")"}, {"name": "option_text", "value": "'Admin'"}], "start": 1758528651877, "stop": 1758528652340}, {"name": "Select option ''Enabled'' from dropdown: ('xpath', \"//label[text()='Status']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")", "status": "passed", "steps": [{"name": "Find element: ('xpath', \"//label[text()='Status']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//label[text()='Status']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")"}], "start": 1758528654910, "stop": 1758528655010}], "parameters": [{"name": "locator", "value": "('xpath', \"//label[text()='Status']/../following-sibling::div//div[contains(@class,'oxd-select-text-input')]\")"}, {"name": "option_text", "value": "'Enabled'"}], "start": 1758528654910, "stop": 1758528655314}], "parameters": [{"name": "role", "value": "'Admin'"}, {"name": "emp_name", "value": "'Thomas Kutty Benny'"}, {"name": "username", "value": "'test_admin_1758528649'"}, {"name": "status", "value": "'Enabled'"}, {"name": "password", "value": "'Test@1234'"}], "start": 1758528651876, "stop": 1758528656195}, {"name": "Wait for success message", "status": "passed", "start": 1758528656195, "stop": 1758528658943}], "start": 1758528649328, "stop": 1758528658943}], "afters": [{"name": "temp_user::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document\n  (Session info: chrome=109.0.5414.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00466643]\n\t(No symbol) [0x003FBE21]\n\t(No symbol) [0x002FDA9D]\n\t(No symbol) [0x003009E4]\n\t(No symbol) [0x003008AD]\n\t(No symbol) [0x00300B30]\n\t(No symbol) [0x00333150]\n\t(No symbol) [0x003269AD]\n\t(No symbol) [0x0034FD7C]\n\t(No symbol) [0x0032641F]\n\t(No symbol) [0x003500D4]\n\t(No symbol) [0x00366B09]\n\t(No symbol) [0x0034FB76]\n\t(No symbol) [0x003249C1]\n\t(No symbol) [0x00325E5D]\n\tGetHandleVerifier [0x006DA142+2497106]\n\tGetHandleVerifier [0x007085D3+2686691]\n\tGetHandleVerifier [0x0070BB9C+2700460]\n\tGetHandleVerifier [0x00513B10+635936]\n\t(No symbol) [0x00404A1F]\n\t(No symbol) [0x0040A418]\n\t(No symbol) [0x0040A505]\n\t(No symbol) [0x0041508B]\n\tBaseThreadInitThunk [0x767B6A24+36]\n\tRtlInitializeExceptionChain [0x778FA9FF+143]\n\tRtlInitializeExceptionChain [0x778FA9CA+90]\n\n", "trace": "  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\MIRZA\\Users\\MIRZAS\\selenium_parallel_project\\tests\\test_admin_page.py\", line 47, in temp_user\n    admin_page.delete_user(username=username)\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\MIRZA\\Users\\MIRZAS\\selenium_parallel_project\\pages\\admin_page.py\", line 187, in delete_user\n    btn.click()\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 120, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 573, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Search user: 'test_admin_1758528649'", "status": "passed", "parameters": [{"name": "username", "value": "'test_admin_1758528649'"}, {"name": "role", "value": "None"}, {"name": "emp_name", "value": "''"}, {"name": "status", "value": "None"}], "start": 1758528671298, "stop": 1758528672704}, {"name": "Search and Delete user: 'test_admin_1758528649'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document\n  (Session info: chrome=109.0.5414.168); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00466643]\n\t(No symbol) [0x003FBE21]\n\t(No symbol) [0x002FDA9D]\n\t(No symbol) [0x003009E4]\n\t(No symbol) [0x003008AD]\n\t(No symbol) [0x00300B30]\n\t(No symbol) [0x00333150]\n\t(No symbol) [0x003269AD]\n\t(No symbol) [0x0034FD7C]\n\t(No symbol) [0x0032641F]\n\t(No symbol) [0x003500D4]\n\t(No symbol) [0x00366B09]\n\t(No symbol) [0x0034FB76]\n\t(No symbol) [0x003249C1]\n\t(No symbol) [0x00325E5D]\n\tGetHandleVerifier [0x006DA142+2497106]\n\tGetHandleVerifier [0x007085D3+2686691]\n\tGetHandleVerifier [0x0070BB9C+2700460]\n\tGetHandleVerifier [0x00513B10+635936]\n\t(No symbol) [0x00404A1F]\n\t(No symbol) [0x0040A418]\n\t(No symbol) [0x0040A505]\n\t(No symbol) [0x0041508B]\n\tBaseThreadInitThunk [0x767B6A24+36]\n\tRtlInitializeExceptionChain [0x778FA9FF+143]\n\tRtlInitializeExceptionChain [0x778FA9CA+90]\n\n", "trace": "  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\MIRZA\\Users\\MIRZAS\\selenium_parallel_project\\pages\\admin_page.py\", line 187, in delete_user\n    btn.click()\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 120, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 573, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\MIRZAS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "username", "value": "'test_admin_1758528649'"}], "start": 1758528672704, "stop": 1758528674202}], "start": 1758528671298, "stop": 1758528674259}], "start": 1758528649328, "stop": 1758528674259}